// export const editorTheme = {
//   ltr: "ltr",
//   rtl: "rtl",
//   placeholder: "editor-placeholder",
//   paragraph: "editor-paragraph",
//   quote: "editor-quote",
//   heading: {
//     h1: "editor-heading-h1",
//     h2: "editor-heading-h2",
//     h3: "editor-heading-h3",
//     h4: "editor-heading-h4",
//     h5: "editor-heading-h5",
//     h6: "editor-heading-h6",
//   },
//   list: {
//     nested: {
//       listitem: "editor-nested-listitem",
//     },
//     ol: "editor-list-ol",
//     ul: "editor-list-ul",
//     listitem: "editor-listItem",
//     listitemChecked: "editor-listItemChecked",
//     listitemUnchecked: "editor-listItemUnchecked",
//   },
//   hashtag: "editor-hashtag",
//   image: "editor-image",
//   link: "editor-link",
//   text: {
//     bold: "editor-textBold",
//     code: "editor-textCode",
//     italic: "editor-textItalic",
//     strikethrough: "editor-textStrikethrough",
//     subscript: "editor-textSubscript",
//     superscript: "editor-textSuperscript",
//     underline: "editor-textUnderline",
//     underlineStrikethrough: "editor-textUnderlineStrikethrough",
//   },
//   code: "editor-code",
//   codeHighlight: {
//     atrule: "editor-tokenAttr",
//     attr: "editor-tokenAttr",
//     boolean: "editor-tokenProperty",
//     builtin: "editor-tokenSelector",
//     cdata: "editor-tokenComment",
//     char: "editor-tokenSelector",
//     class: "editor-tokenFunction",
//     "class-name": "editor-tokenFunction",
//     comment: "editor-tokenComment",
//     constant: "editor-tokenProperty",
//     deleted: "editor-tokenProperty",
//     doctype: "editor-tokenComment",
//     entity: "editor-tokenOperator",
//     function: "editor-tokenFunction",
//     important: "editor-tokenVariable",
//     inserted: "editor-tokenSelector",
//     keyword: "editor-tokenAttr",
//     namespace: "editor-tokenVariable",
//     number: "editor-tokenProperty",
//     operator: "editor-tokenOperator",
//     prolog: "editor-tokenComment",
//     property: "editor-tokenProperty",
//     punctuation: "editor-tokenPunctuation",
//     regex: "editor-tokenVariable",
//     selector: "editor-tokenSelector",
//     string: "editor-tokenSelector",
//     symbol: "editor-tokenProperty",
//     tag: "editor-tokenProperty",
//     url: "editor-tokenOperator",
//     variable: "editor-tokenVariable",
//   },
// };

export const editorTheme = {
  ltr: "ltr",
  rtl: "rtl",
  placeholder: "placeholder",
  paragraph: "paragraph",
  quote: "quote",
  heading: {
    h1: "text-4xl font-bold",
    h2: "text-3xl font-bold",
    h3: "text-2xl font-bold",
    h4: "text-xl font-bold",
    h5: "text-lg font-bold",
    h6: "text-base font-bold",
  },
  list: {
    nested: {
      listitem: "ml-8",
    },
    ol: "list-decimal",
    ul: "list-disc",
    listitem: "listitem",
    listitemChecked: "listitem-checked",
    listitemUnchecked: "listitem-unchecked",
  },
  hashtag: "hashtag",
  image: "image",
  link: "link",
  text: {
    bold: "font-bold",
    code: "font-mono",
    italic: "italic",
    strikethrough: "line-through",
    subscript: "sub",
    superscript: "sup",
    underline: "underline",
    underlineStrikethrough: "underline line-through",
  },
  code: "code",
  codeHighlight: {
    atrule: "token-atrule",
    attr: "token-attr",
    boolean: "token-boolean",
    builtin: "token-builtin",
    cdata: "token-cdata",
    char: "token-char",
    class: "token-class",
    "class-name": "token-class-name",
    comment: "token-comment",
    constant: "token-constant",
    deleted: "token-deleted",
    doctype: "token-doctype",
    entity: "token-entity",
    function: "token-function",
    important: "token-important",
    inserted: "token-inserted",
    keyword: "token-keyword",
    namespace: "token-namespace",
    number: "token-number",
    operator: "token-operator",
    prolog: "token-prolog",
    property: "token-property",
    punctuation: "token-punctuation",
    regex: "token-regex",
    selector: "token-selector",
    string: "token-string",
    symbol: "token-symbol",
    tag: "token-tag",
    url: "token-url",
    variable: "token-variable",
  },
};
