import "./styles/globals.css";
import Navigation from "../components/Navigation/Navigation";
export const metadata = {
  title: "Delali Dogbevi",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" px-5 lg:px-32">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
